language: r
sudo: required
dist: xenial
cache: packages
warnings_are_errors: false

apt_packages:
  - libgmp3-dev
  - libmagick++-dev

before_install:
  - cd pkg

r:
  - release
  - devel
  - oldrel
os:
  - linux
  
matrix:
  include:
    - r: release
      os: osx
