language: r
sudo: required
dist: trusty
cache: packages
warnings_are_errors: false

apt_packages:
  - libgmp3-dev

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

before_install:
  - cd pkg

r:
  - release
  - devel
  
matrix:
  include:
    - r: release
      os: osx
    - r: release
      os: linux

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

