language: r
sudo: required
dist: trusty

before_install:
  - cd pkg

r:
  - release
  - devel

os:
  - linux
  
matrix:
  include:
    - r: release
      os: osx

apt_packages:
  - libgmp3-dev

cache: packages

warnings_are_errors: false

